### PR TITLE
on Onion Location

### PR DESCRIPTION
**Pull request by vv01f**
documenting possibility for redirect to Onion Location

### CODE REVIEW

**Comment by luto** [comment]
Nice idea! Can you change this so it uses `uberspace web header` as documented in #145 and remove the meta-tag hint?

**Comment by vv01f** [comment]
of course, just saw the changelog via mastodon and thought of adding it

**Comment by luto** [comment]
it will probably be available on monday or tuesday.

**Comment by luto** [comment]
thank you"!

**Pull request merged**
